### ISSUE TITLE
HU-17 CREACION DE DIAGRAMA DE ENTIDAD-RELACION

### ISSUE THREAD

**Issue by Nahuel95** [pgPilfs/pil-money-g3a-team-3a#19]

**Comment by luciagrosso** [comment]
![V1 2- Diagrama ER y tabulacion](https://user-images.githubusercontent.com/83891522/128274527-b8d82b14-2352-440e-9607-d52361cf51db.jpeg)
![V1- Diagrama ER y tabulacion](https://user-images.githubusercontent.com/83891522/128274535-9ea45a80-2ebf-4c5a-96dc-ee4ccbf998c1.jpg)
